import "server-only";
import { prisma } from "./prisma";
import { enqueue, processOutbox, renderByKey, getProfile } from "./wa";
import { formatCurrency, formatDate } from "./utils";

export type SchedulerReport = {
  ranAt: string;
  trashReminders: number;
  activityReminders: number;
  autoGenerated: number;
  delivery: { processed: number; sent: number; failed: number };
  details: string[];
};

function startOfDay(d: Date) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}

function addDays(d: Date, days: number) {
  const x = new Date(d);
  x.setDate(x.getDate() + days);
  return x;
}

const TRASH_TEMPLATE: Record<number, string> = {
  [-3]: "TRASH_PRE",
  0: "TRASH_DUE",
  3: "TRASH_LATE_3",
  7: "TRASH_LATE_7",
};

function fallbackTrashText(offset: number) {
  if (offset < 0) {
    return `Halo Bapak/Ibu {{nama}} 👋\nMengingatkan, iuran kebersihan RW {{nama_rw}} periode {{periode}} sebesar {{jumlah}} akan jatuh tempo pada {{jatuh_tempo}} ({{hari_lagi}} hari lagi).\n\nMohon dapat disiapkan dan dibayarkan melalui ketua RT atau transfer ke rekening kas RW.\nTerima kasih 🙏`;
  }
  if (offset === 0) {
    return `Halo Bapak/Ibu {{nama}} 👋\nHari ini adalah *jatuh tempo* iuran kebersihan RW {{nama_rw}} periode {{periode}} sebesar {{jumlah}}.\n\nSilakan lakukan pembayaran hari ini agar tetap tertib administrasi.\nTerima kasih 🙏`;
  }
  return `Halo Bapak/Ibu {{nama}} 🙏\nIuran kebersihan RW {{nama_rw}} periode {{periode}} sebesar {{jumlah}} *belum kami terima* dan sudah lewat {{hari_terlambat}} hari dari jatuh tempo ({{jatuh_tempo}}).\n\nMohon konfirmasi jika sudah membayar, atau segera lunasi melalui ketua RT masing-masing.\nTerima kasih.`;
}

/** Kirim pengingat tagihan sampah sesuai jadwal (H-3, H, H+3, H+7). */
export async function runTrashReminders(details: string[]) {
  const profile = await getProfile();
  const offsets = profile.reminderOffsets
    .split(",")
    .map((o) => Number(o.trim()))
    .filter((n) => !Number.isNaN(n));

  const now = new Date();
  const windowStart = addDays(startOfDay(now), -Math.max(0, ...offsets) - 40);
  const windowEnd = addDays(startOfDay(now), 40);

  const bills = await prisma.wasteBill.findMany({
    where: {
      status: { in: ["BELUM_BAYAR", "MENUNGGU_KONFIRMASI"] },
      dueDate: { gte: windowStart, lte: windowEnd },
    },
    include: {
      family: { include: { head: true, rt: true } },
      payer: true,
    },
  });

  let count = 0;
  for (const bill of bills) {
    // Tentukan offset yang sudah waktunya dikirim dan belum pernah dikirim.
    const due = startOfDay(bill.dueDate);
    for (const offset of offsets.sort((a, b) => a - b)) {
      const trigger = addDays(due, offset);
      trigger.setHours(profile.reminderHour, 0, 0, 0);
      if (now < trigger) continue;

      const key = `TRASH_${bill.id}_${offset}`;
      const existing = await prisma.waMessage.findFirst({
        where: {
          relatedId: bill.id,
          relatedType: "WasteBill",
          templateKey: key,
          status: { in: ["TERKIRIM", "TERKIRIM_SIMULASI", "ANTRIAN"] },
        },
      });
      if (existing) continue;

      const person = bill.payer ?? bill.family.head;
      const phone = person?.whatsapp ?? person?.phone;
      if (!phone) continue;

      const templateKey = TRASH_TEMPLATE[offset];
      const vars = {
        nama: person?.name ?? bill.family.headName,
        no_kk: bill.family.kkNumber,
        rt: bill.family.rt.number,
        periode: `${new Date(bill.periodYear, bill.periodMonth - 1, 1).toLocaleString("id-ID", {
          month: "long",
        })} ${bill.periodYear}`,
        jatuh_tempo: formatDate(bill.dueDate),
        jumlah: formatCurrency(bill.amount),
        hari_terlambat: offset,
        hari_lagi: Math.abs(offset),
      };

      const body =
        (templateKey ? await renderByKey(templateKey, vars) : null) ??
        renderFallback(fallbackTrashText(offset), vars, profile);

      await enqueue({
        toPhone: phone,
        toName: person?.name ?? bill.family.headName,
        body,
        category: "PENGINGAT_SAMPAH",
        templateKey: key,
        relatedType: "WasteBill",
        relatedId: bill.id,
        sendImmediately: false,
      });

      await prisma.wasteBill.update({
        where: { id: bill.id },
        data: {
          lastReminderAt: now,
          lastReminderKey: String(offset),
          reminderCount: { increment: 1 },
        },
      });
      count++;
      details.push(`Pengingat iuran ${offset >= 0 ? "H+" + offset : "H" + offset} → ${person?.name} (RT ${bill.family.rt.number})`);
    }
  }
  return count;
}

function renderFallback(tpl: string, vars: Record<string, string | number>, profile: Awaited<ReturnType<typeof getProfile>>) {
  return tpl.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_m, key: string) => {
    const map: Record<string, string> = {
      nama_rw: `RW ${profile.rwNumber}`,
    };
    return String(map[key] ?? (vars as Record<string, string | number>)[key] ?? "-");
  });
}

/** Kirim pengingat jadwal kegiatan (kerja bakti, ronda, dll). */
export async function runActivityReminders(details: string[]) {
  const profile = await getProfile();
  if (!profile.activityReminder) return 0;

  const now = new Date();
  const until = new Date(now.getTime() + profile.activityLeadHours * 3600_000);

  const activities = await prisma.activity.findMany({
    where: {
      status: "TERENCANA",
      reminderSentAt: null,
      startsAt: { gte: now, lte: until },
    },
    include: {
      rt: true,
      assignments: { include: { resident: true } },
    },
  });

  let count = 0;
  for (const activity of activities) {
    const assigned = activity.assignments.map((a) => a.resident).filter((r) => r.status === "AKTIF");
    let recipients = assigned;

    if (!recipients.length) {
      recipients = await prisma.resident.findMany({
        where: {
          status: "AKTIF",
          familyRole: "KEPALA",
          ...(activity.rtId ? { rtId: activity.rtId } : {}),
        },
      });
    }

    const vars = {
      kegiatan: activity.title,
      tanggal: formatDate(activity.startsAt, true),
      jam: `${String(new Date(activity.startsAt).getHours()).padStart(2, "0")}.${String(
        new Date(activity.startsAt).getMinutes(),
      ).padStart(2, "0")} - ${String(new Date(activity.endsAt).getHours()).padStart(2, "0")}.${String(
        new Date(activity.endsAt).getMinutes(),
      ).padStart(2, "0")}`,
      lokasi: activity.location,
      penanggung_jawab: activity.picName,
      rt: activity.rt?.number ?? "RW",
    };

    for (const person of recipients) {
      const phone = person.whatsapp ?? person.phone;
      if (!phone) continue;
      const body =
        (await renderByKey("ACTIVITY_REMINDER", { ...vars, nama: person.name })) ??
        `Halo Bapak/Ibu ${person.name} 👋\nMengingatkan jadwal *${activity.title}* RW ${profile.rwNumber}:\n📅 ${vars.tanggal}\n🕐 ${vars.jam}\n📍 ${activity.location}\n\nMohon kehadirannya tepat waktu. Terima kasih 🙏`;

      await enqueue({
        toPhone: phone,
        toName: person.name,
        body,
        category: "JADWAL_KEGIATAN",
        templateKey: `ACTIVITY_${activity.id}`,
        relatedType: "Activity",
        relatedId: activity.id,
        sendImmediately: false,
      });
      count++;
    }

    if (recipients.length) {
      await prisma.activity.update({
        where: { id: activity.id },
        data: { reminderSentAt: now, reminderCount: { increment: 1 } },
      });
      details.push(`Pengingat kegiatan "${activity.title}" → ${recipients.length} warga`);
    }
  }
  return count;
}

/** Generate tagihan bulanan otomatis (untuk periode berjalan bila belum ada). */
export async function autoGenerateBills(details: string[]) {
  const profile = await getProfile();
  const now = new Date();
  const month = now.getMonth() + 1;
  const year = now.getFullYear();

  const existing = await prisma.wasteBill.count({ where: { periodMonth: month, periodYear: year } });
  if (existing > 0) return 0;

  const families = await prisma.family.findMany({
    where: { members: { some: { status: "AKTIF" } } },
    include: { head: true, rt: true },
  });

  const dueDate = new Date(year, month - 1, profile.trashDueDay, 23, 59, 0);
  let created = 0;
  for (const family of families) {
    const amount = family.economicStatus === "KURANG_MAMPU" ? Math.round(profile.trashFeeAmount / 2) : profile.trashFeeAmount;
    try {
      await prisma.wasteBill.create({
        data: {
          billNumber: `INV/${year}${String(month).padStart(2, "0")}/${family.rt.number}/${
            family.kkNumber.slice(-4)
          }`,
          familyId: family.id,
          payerId: family.headId,
          rtId: family.rtId,
          periodMonth: month,
          periodYear: year,
          amount,
          dueDate,
        },
      });
      created++;
    } catch {
      // tagihan sudah ada
    }
  }
  if (created) details.push(`Tagihan otomatis periode ${month}/${year} → ${created} KK`);
  return created;
}

export async function runScheduler(): Promise<SchedulerReport> {
  const profile = await getProfile();
  const details: string[] = [];

  if (!profile.waAutoSend) {
    return {
      ranAt: new Date().toISOString(),
      trashReminders: 0,
      activityReminders: 0,
      autoGenerated: 0,
      delivery: { processed: 0, sent: 0, failed: 0 },
      details: ["Penjadwal otomatis nonaktif dari Pengaturan."],
    };
  }

  const autoGenerated = await autoGenerateBills(details);
  const trashReminders = await runTrashReminders(details);
  const activityReminders = await runActivityReminders(details);
  const delivery = await processOutbox(200);

  return {
    ranAt: new Date().toISOString(),
    trashReminders,
    activityReminders,
    autoGenerated,
    delivery,
    details,
  };
}
