"use client";

import * as React from "react";
import Link from "next/link";
import { UsersRound, Users, Wallet, AlertTriangle, Send, RefreshCw } from "lucide-react";
import { useResource } from "@/hooks/use-collection";
import { post } from "@/lib/client/api";
import { Card, CardHeader, Button } from "@/components/ui/primitives";
import { ErrorState } from "@/components/ui/states";
import { PageHeader } from "@/components/layout/app-shell";
import { useTheme } from "@/components/providers";
import { toast } from "sonner";
import { formatCurrency, formatNumber } from "@/lib/utils";
import {
  StatCard,
  CollectionChart,
  UpcomingActivities,
  ActivityFeed,
  TopDebtors,
  RtBreakdown,
  WaSummary,
  DashboardSkeleton,
  type DashboardStats,
} from "@/components/dashboard";

export default function DashboardPage() {
  const { data, isLoading, error, refresh } = useResource<DashboardStats>("/api/stats");
  const [running, setRunning] = React.useState(false);
  useTheme();

  async function runScheduler() {
    setRunning(true);
    try {
      const res = await post<{
        summary: { trashReminders: number; activityReminders: number; autoGenerated: number; delivery: { sent: number; failed: number } };
      }>("/api/wa/run");
      const s = res.summary;
      toast.success(
        `Penjadwal selesai: ${s.trashReminders} pengingat iuran · ${s.activityReminders} pengingat kegiatan · ${s.delivery.sent} pesan terkirim`,
      );
      refresh();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Gagal menjalankan penjadwal");
    } finally {
      setRunning(false);
    }
  }

  if (isLoading) return <DashboardSkeleton />;
  if (error || !data)
    return <ErrorState message="Gagal memuat data dashboard" onRetry={() => refresh()} />;

  return (
    <div className="animate-fade-in space-y-5">
      <PageHeader
        title="Dashboard"
        description={`Ringkasan RW 05 · periode iuran ${data.period.label}`}
        actions={
          <>
            <Button variant="secondary" size="sm" onClick={() => refresh()}>
              <RefreshCw className="h-3.5 w-3.5" />
              Muat ulang
            </Button>
            <Button size="sm" onClick={runScheduler} loading={running}>
              {!running && <Send className="h-3.5 w-3.5" />}
              Kirim pengingat sekarang
            </Button>
          </>
        }
      />

      {/* Statistik utama */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Kartu Keluarga"
          value={formatNumber(data.counts.families)}
          hint={`${data.counts.rt} RT terdaftar`}
          icon={UsersRound}
          tone="primary"
          href="/dashboard/keluarga"
        />
        <StatCard
          label="Data Warga"
          value={formatNumber(data.counts.residents)}
          hint={`${formatNumber(data.counts.activeResidents)} aktif · ${data.counts.male} L / ${data.counts.female} P`}
          icon={Users}
          tone="info"
          href="/dashboard/warga"
        />
        <StatCard
          label="Iuran terkumpul"
          value={formatCurrency(data.bills.collected)}
          hint={`${data.bills.paid} dari ${data.bills.current} KK lunas`}
          icon={Wallet}
          tone="success"
          footer={
            <div className="flex items-center gap-2">
              <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-surface-muted">
                <div
                  className="h-full rounded-full bg-success transition-all duration-700"
                  style={{ width: `${data.bills.collectionRate}%` }}
                />
              </div>
              <span className="text-[11.5px] font-semibold tabular-nums text-success">
                {data.bills.collectionRate}%
              </span>
            </div>
          }
        />
        <StatCard
          label="Tunggakan berjalan"
          value={formatCurrency(data.bills.outstanding)}
          hint={`${data.bills.unpaid} KK belum membayar`}
          icon={AlertTriangle}
          tone="danger"
          href="/dashboard/iuran"
        />
      </div>

      {/* Grafik & kegiatan */}
      <div className="grid min-w-0 grid-cols-1 gap-4 lg:grid-cols-3">
        <Card className="min-w-0 lg:col-span-2">
          <CardHeader
            title="Penerimaan iuran kebersihan"
            description="6 bulan terakhir: terkumpul vs target"
            action={
              <div className="flex items-center gap-3 text-[11.5px] text-muted">
                <span className="flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 rounded-sm bg-line-strong" />
                  Target
                </span>
                <span className="flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 rounded-sm bg-success" />
                  Terkumpul
                </span>
              </div>
            }
          />
          <CollectionChart data={data.months} />
        </Card>

        <Card>
          <CardHeader
            title="Kegiatan mendatang"
            description="Jadwal kerja bakti, ronda & rapat"
            action={
              <Link href="/dashboard/kegiatan" className="text-[12px] font-medium text-primary hover:underline">
                Semua
              </Link>
            }
          />
          <UpcomingActivities items={data.upcomingActivities} />
        </Card>
      </div>

      {/* Tunggakan, RT, WhatsApp */}
      <div className="grid min-w-0 grid-cols-1 gap-4 lg:grid-cols-3">
        <Card>
          <CardHeader
            title="Tunggakan teratas"
            description="Segera tindak lanjuti"
            action={
              <Link href="/dashboard/iuran" className="text-[12px] font-medium text-primary hover:underline">
                Kelola
              </Link>
            }
          />
          <TopDebtors items={data.topDebtors} />
        </Card>

        <Card>
          <CardHeader title="Kepatuhan per RT" description={`Periode ${data.period.label}`} />
          <div className="max-h-[330px] overflow-y-auto scrollbar-thin">
            <RtBreakdown items={data.rtStats} />
          </div>
        </Card>

        <div className="space-y-4">
          <Card>
            <CardHeader
              title="WhatsApp"
              description="Pengingat & siaran ke warga"
              action={
                <Link href="/dashboard/whatsapp" className="text-[12px] font-medium text-primary hover:underline">
                  Log
                </Link>
              }
            />
            <WaSummary wa={data.wa} />
          </Card>

          <Card>
            <CardHeader title="Surat pengantar" description="Status permohonan warga" />
            <div className="grid grid-cols-2 gap-2.5 p-5 pt-0">
              {[
                { label: "Diajukan", value: data.letters.DIAJUKAN ?? 0, tone: "warning" as const },
                { label: "Diproses", value: data.letters.DIPROSES ?? 0, tone: "info" as const },
                { label: "Selesai", value: data.letters.SELESAI ?? 0, tone: "success" as const },
                { label: "Ditolak", value: data.letters.DITOLAK ?? 0, tone: "danger" as const },
              ].map((s) => (
                <Link
                  key={s.label}
                  href="/dashboard/surat"
                  className="rounded-xl border border-line bg-surface-muted/50 px-3 py-2.5 transition-colors hover:bg-surface-muted"
                >
                  <p className="text-[11px] text-muted">{s.label}</p>
                  <p className="text-lg font-bold tabular-nums">{s.value}</p>
                </Link>
              ))}
            </div>
          </Card>
        </div>
      </div>

      {/* Log aktivitas */}
      <Card>
        <CardHeader title="Aktivitas terbaru" description="Catatan perubahan data oleh pengurus" />
        <div className="max-h-[380px] overflow-y-auto scrollbar-thin">
          <ActivityFeed items={data.recentLogs} />
        </div>
      </Card>
    </div>
  );
}
